feat : add command /pointchange
waiwai-developers/waiwaichan pull request #128
Opened 2024-11-10 11:19 UTC by wautopia

2024-11-10 12:56 UTC, y1wtt requested changes

2024-11-10 12:56 UTC, y1wtt commented on routes/discordjs/interaction.js
> +					await interaction.reply( await pointChange(interaction.user.id, interaction.options.getString("id")));
idは常にIntegerなので、getStringではなくgetIntegerを使って取ってください

2024-11-10 12:56 UTC, y1wtt commented on logics/pointChange.mjs
> +					itemId: itemId,
itemIdではなくidでwhereを指定してください (多分さっき修正していたのものをpushするだけかと)

2024-11-10 14:16 UTC, mamepon2580 commented on logics/index.mjs
> +export { pointChange } from "./pointChange.mjs";
@wautopia 
細かいですがここ改行の追加お願いします！

2024-11-10 14:19 UTC, mamepon2580 commented
@wautopia 
以下の実行をお願いします！
```
npm run lint:unsafe
```

2024-11-10 15:07 UTC, mamepon2580 commented on routes/discordjs/registration.js
> +		.addStringOption((option) =>
@wautopia 
杏仁さんの修正プラス以下も修正する必要があります！
```
.addIntegerOption((option) =>
	option.setName("id").setDescription("integer").setRequired(true),
)
```

2024-11-10 15:48 UTC, mamepon2580 commented on logics/pointChange.mjs
> +		const userItem = await models.UserItem.update(
ここ検証したところ必ずオブジェクトが取れてしまうので以下で一回取得し存在のチェックをして欲しいです！
```js
		const userItem = await models.UserItem.findOne(
			{
				where: {
					id: userItemId,
					userId: userId,
					status: models.UserItem.STATUS_VALID,
					expiredAt: {[Sequelize.Op.gte]: date}
				}
			}
		)

```

2024-11-10 15:48 UTC, mamepon2580 commented on logics/pointChange.mjs
> +
上記のコメントの続きなのですがここでupdateするようにしましょう！
```js
		await userItem.update({ status: models.UserItem.STATUS_INVALID });
```

2024-11-10 16:08 UTC, wautopia commented on routes/discordjs/interaction.js
> +					await interaction.reply( await pointChange(interaction.user.id, interaction.options.getString("id")));
こちら修正しました。

commit log : https://github.com/waiwai-developers/waiwaichan/pull/128/commits/4ae5c9cac77f211adbac80b9da05014b56d9901f

2024-11-10 16:10 UTC, wautopia commented on logics/index.mjs
> +export { pointChange } from "./pointChange.mjs";
修正しました。

commit log : https://github.com/waiwai-developers/waiwaichan/pull/128/commits/2913c42ec611a2521231cbb2962a098b9d842ad6

2024-11-10 16:12 UTC, wautopia commented on routes/discordjs/registration.js
> +		.addStringOption((option) =>
修正しました。

commit log : https://github.com/waiwai-developers/waiwaichan/pull/128/commits/ded3f08f33e856b432a3968502d2840a06ff45a5

2024-11-10 16:12 UTC, wautopia commented on logics/pointChange.mjs
> +		const userItem = await models.UserItem.update(
修正しました。

commit log : https://github.com/waiwai-developers/waiwaichan/pull/128/commits/ded3f08f33e856b432a3968502d2840a06ff45a5

2024-11-10 16:12 UTC, wautopia commented on logics/pointChange.mjs
> +
修正しました。

commit log : https://github.com/waiwai-developers/waiwaichan/pull/128/commits/ded3f08f33e856b432a3968502d2840a06ff45a5

2024-11-10 16:18 UTC, y1wtt commented
[ドキュメント](https://sequelize.org/api/v6/class/src/model.js~model)によると
`Promise<Array<number, number>>` の値をUpdateは返すのでfindOne→UpdateするよりもUpdateをLIMIT1で走らせて結果の `result[0] > 0` で判別するとクエリ発行回数を減らせると思います

2024-11-10 17:26 UTC, y1wtt submitted a review, later dismissed
寝るのであとは頼みます

2024-11-10 18:50 UTC, wautopia commented
>  [ドキュメント](https://sequelize.org/api/v6/class/src/model.js~model#static-method-update)によると
> 
> The first element is always the number of affected rows
> 
> とあり Promise<Array<number, number>> の最初の値はUpdateの影響行数返すのでfindOne→UpdateするよりもUpdateをLIMIT1で走らせて結果の result[0] > 0 で判別するとクエリ発行回数を減らせると思います

修正させて頂きました。

commit log : https://github.com/waiwai-developers/waiwaichan/pull/128/commits/1bae7433753be5e3a39500d3ecd50e815f5cf0d6

2024-11-14 16:18 UTC, mamepon2580 reviewed
LGTM

2024-11-14 16:18 UTC, mamepon2580 approved these changes

2024-11-14 16:37 UTC, y1wtt commented on logics/pointChange.js
> +		await userItem.update({ status: UserItem.STATUS_INVALID });
update でロックを先に確保したいので、今後Selectの前にupdateを行いたいです。
でも、今回のスコープではないので、一旦マージしてよいかと！

2024-11-14 16:42 UTC, y1wtt approved these changes
LGTM

2024-11-14 16:55 UTC, merged