feature: separate dev and prod
waiwai-developers/waiwaichan pull request #236
Opened 2024-11-22 18:05 UTC by mamepon2580

2024-11-22 18:09 UTC, mamepon2580 commented
Cloud SQL Auth Proxy Docker イメージを使用した SQL サーバー クライアントの接続 
https://cloud.google.com/sql/docs/sqlserver/connect-docker?hl=ja

2024-11-23 02:33 UTC, y1wtt approved these changes

2024-11-23 02:33 UTC, y1wtt commented on package-lock.json
- #198 
このプルリクで統一するまで一旦paclkage-lock.json更新したくないです
`git restore package-lock json` で戻してもらえると！

2024-11-23 02:33 UTC, y1wtt commented on environment/develop/docker-compose.yml
> +      dockerfile: ./Dockerfile
`environment/develop/docker-compose.yml`とするならDockerfileも `environment/develop/Dockerfile`としたいです。

2024-11-23 02:33 UTC, y1wtt requested changes
間違えました

2024-11-23 04:40 UTC, mamepon2580 commented on environment/develop/docker-compose.yml
> +      dockerfile: ./Dockerfile
こちらの方がいいかなと考えていました！修正しました！

commit log: https://github.com/waiwai-developers/waiwaichan/pull/236/commits/cd945f69251b5609365b7a00efa1f623012719be

2024-11-23 14:20 UTC, y1wtt reviewed
あと、Readme更新してもらえたらOKです

2024-11-23 14:32 UTC, mamepon2580 commented
@y1wtt 
こちら修正しました！

commit log: https://github.com/waiwai-developers/waiwaichan/pull/236/commits/e81f5f011f38251d0b21c75fafb63a23c53e830a https://github.com/waiwai-developers/waiwaichan/pull/236/commits/3d3fdec8866f2f078f2d51fcc77e05440cb5db36

2024-11-23 14:38 UTC, merged