fix remainder soft delete
waiwai-developers/waiwaichan pull request #318
Opened 2024-11-29 12:33 UTC by mamepon2580

2024-11-29 17:03 UTC, y1wtt requested changes

2024-11-29 17:03 UTC, y1wtt commented on src/entities/vo/ReminderStatus.ts
> +	static INVALID = new ReminderStatus(false);
deletedAtを使ってほしいです
https://sequelize.org/docs/v6/core-concepts/paranoid/

2024-11-30 04:19 UTC, mamepon2580 commented on src/entities/vo/ReminderStatus.ts
> +	static INVALID = new ReminderStatus(false);
こちらで修正しました！

commit: https://github.com/waiwai-developers/waiwaichan/pull/318/commits/1c3ec488f82a2eb46ed317f15b99495867122783

2024-11-30 06:27 UTC, y1wtt requested changes
処理に関しては問題なさそうです
Interfaceの修正に関していくつか疑問点を挙げました

2024-11-30 15:07 UTC, mamepon2580 commented on src/logics/Interfaces/logics/IReminderLogic.ts
> +	create(
@y1wtt 
渡すデータとしておそらくid: UserPointItemIdが必要ないのではないかと考えています！

2024-11-30 15:07 UTC, mamepon2580 commented on src/logics/Interfaces/repositories/database/IReminderRepository.ts
> +	create(
@y1wtt
渡すデータとしておそらくid: UserPointItemIdが必要ないのではないかと考えています！

2024-11-30 15:10 UTC, mamepon2580 commented on src/repositories/sequelize-mysql/ReminderRepositoryImpl.ts
> +	async destoryReminder(
こちらおそらくupdateReminderにstatusにした時かえてそのあと元の名前に戻すつもりが違う名前になってますね！修正しました！！

commitlog: https://github.com/waiwai-developers/waiwaichan/pull/318/commits/6fc47e03c595f6f132cb9cdcd65fdc54384aabfa

2024-11-30 15:11 UTC, mamepon2580 commented on src/entities/dto/ReminderDto.ts
> +		public deletedAt: ReminderDeletedAt,
確かに必要ないですね、僕もその認識です！削除しました！！

commitlog: https://github.com/waiwai-developers/waiwaichan/pull/318/commits/6b4d927701035d88d25196681c13791aa8c32083

2024-12-01 06:05 UTC, mamepon2580 commented on src/logics/Interfaces/logics/IReminderLogic.ts
> +	create(
逆にcreateする時に使わないのでdtoからidを抜くのはどうでしょうか？

2024-12-01 06:16 UTC, y1wtt commented on src/logics/Interfaces/logics/IReminderLogic.ts
> +	create(
Dtoはcreateでないときにも利用されます
ex.) findByUserId
https://github.com/waiwai-developers/waiwaichan/blob/9e190b80fdc36f62368199f4a8bbd8a6c49e2209/src/logics/Interfaces/repositories/database/IReminderRepository.ts#L8
この場合IDは必要です。

2024-12-01 06:23 UTC, mamepon2580 commented on src/logics/Interfaces/logics/IReminderLogic.ts
> +	create(
逆にdeleteReminderでdto使ってないのは何故でしょうか？

2024-12-01 06:27 UTC, y1wtt commented on src/logics/Interfaces/logics/IReminderLogic.ts
> +	create(
@mamepon2580 
deleteReminderは抽象的にどういう関数かというと、Keyを使ってValueを消す関数です
そしてdeleteでは何が消えたか、というのは呼び出し側が関心がなく成功か失敗かというところです
消す側は何を消すか知っているからidを知っているので

2024-12-01 14:24 UTC, mamepon2580 commented on src/logics/Interfaces/logics/IReminderLogic.ts
> +	create(
@y1wtt 
dtoとはdata transfer objectの略だと思うのですが本質的に概念がちょっと曖昧な気がしていて「存在する全てのparameterを含む」のか「全てに共通する必要最低限のparameterを含む」のかどちらかがいい気がしているのですが、そこは本来あいまいでも良いものなのでしょうか？

2024-12-01 14:30 UTC, y1wtt commented on src/logics/Interfaces/logics/IReminderLogic.ts
> +	create(
モノ=objectという概念があるので、現実世界のモノとの1:1の関係性を持ちたいという感じですかね。
ルールベースではなく、実態ベースな感じです。

2024-12-01 14:33 UTC, mamepon2580 commented on src/logics/Interfaces/logics/IReminderLogic.ts
> +	create(
それであれば僕も納得です！それに合わせて修正しますね！！

2024-12-01 15:46 UTC, mamepon2580 commented on src/logics/Interfaces/logics/IReminderLogic.ts
> +	create(
@y1wtt 
こちら修正しました！ナイスレビュー！！

commit log: https://github.com/waiwai-developers/waiwaichan/pull/318/commits/1460708b055f699f8b1ca5dc6946a0e86e986eea

2024-12-01 15:49 UTC, y1wtt requested changes

2024-12-01 15:49 UTC, y1wtt commented on src/entities/dto/ReminderDto.ts
> +		public id: ReminderId | null,
null不使用したいです
undefinedに統一したいです
理由として `typeof null === "object"`がtrueだからです

2024-12-01 15:51 UTC, y1wtt reviewed
null →undefined修正お願いします

2024-12-01 15:51 UTC, y1wtt commented on src/repositories/sequelize-mysql/ReminderSchedulerRepositoryImpl.ts
> +				deletedAt: null,
これもnull→undefinedにしたいです

2024-12-01 15:51 UTC, y1wtt commented on src/repositories/sequelize-mysql/ReminderRepositoryImpl.ts
> +				deletedAt: null,
これもnull→undefinedにしたいです

2024-12-01 15:51 UTC, y1wtt commented on src/repositories/sequelize-mysql/ReminderRepositoryImpl.ts
> +			deletedAt: null,
これもnull→undefinedにしたいです

2024-12-01 15:52 UTC, y1wtt reviewed
null →undefined修正お願いします

2024-12-01 15:52 UTC, y1wtt commented on src/routes/discordjs/events/SlashCommandRouter.ts
> +									null,
これもですね

2024-12-01 16:09 UTC, mamepon2580 commented on src/repositories/sequelize-mysql/ReminderSchedulerRepositoryImpl.ts
> +				deletedAt: null,
SQL以外はundefinedで大丈夫そうなのですが以下はエラーがでますね！
```
waiwai-scheduler  | Error: Error: WHERE parameter "deletedAt" has invalid "undefined" value
waiwai-scheduler  |     at MySQLQueryGenerator.whereItemQuery (/app/node_modules/sequelize/src/dialects/abstract/query-generator.js:2451:13)
waiwai-scheduler  |     at <anonymous> (/app/node_modules/sequelize/src/dialects/abstract/query-generator.js:2440:25)
waiwai-scheduler  |     at Array.forEach (<anonymous>)
waiwai-scheduler  |     at MySQLQueryGenerator.whereItemsQuery (/app/node_modules/sequelize/src/dialects/abstract/query-generator.js:2438:35)
waiwai-scheduler  |     at <anonymous> (/app/node_modules/sequelize/src/dialects/abstract/query-generator.js:2574:30)
waiwai-scheduler  |     at Array.map (<anonymous>)
waiwai-scheduler  |     at MySQLQueryGenerator._whereGroupBind (/app/node_modules/sequelize/src/dialects/abstract/query-generator.js:2573:21)
waiwai-scheduler  |     at MySQLQueryGenerator.whereItemQuery (/app/node_modules/sequelize/src/dialects/abstract/query-generator.js:2509:19)
waiwai-scheduler  |     at <anonymous> (/app/node_modules/sequelize/src/dialects/abstract/query-generator.js:2440:25)
waiwai-scheduler  |     at Array.forEach (<anonymous>)
```

2024-12-01 16:10 UTC, mamepon2580 commented on src/repositories/sequelize-mysql/ReminderRepositoryImpl.ts
> +				deletedAt: null,
SQL以外はundefinedで大丈夫そうなのですが以下はエラーがでますね！
```
waiwai-backend    | Executing (c1a472df-d42b-4310-ae6c-c1a974e0d293): START TRANSACTION;
waiwai-backend    | Executing (c1a472df-d42b-4310-ae6c-c1a974e0d293): ROLLBACK;
waiwai-backend    | Error: WHERE parameter "deletedAt" has invalid "undefined" value
waiwai-backend    |     at MySQLQueryGenerator.whereItemQuery (/app/node_modules/sequelize/src/dialects/abstract/query-generator.js:2451:13)
waiwai-backend    |     at <anonymous> (/app/node_modules/sequelize/src/dialects/abstract/query-generator.js:2440:25)
waiwai-backend    |     at Array.forEach (<anonymous>)
waiwai-backend    |     at MySQLQueryGenerator.whereItemsQuery (/app/node_modules/sequelize/src/dialects/abstract/query-generator.js:2438:35)
waiwai-backend    |     at <anonymous> (/app/node_modules/sequelize/src/dialects/abstract/query-generator.js:2574:30)
waiwai-backend    |     at Array.map (<anonymous>)
waiwai-backend    |     at MySQLQueryGenerator._whereGroupBind (/app/node_modules/sequelize/src/dialects/abstract/query-generator.js:2573:21)
waiwai-backend    |     at MySQLQueryGenerator.whereItemQuery (/app/node_modules/sequelize/src/dialects/abstract/query-generator.js:2509:19)
waiwai-backend    |     at <anonymous> (/app/node_modules/sequelize/src/dialects/abstract/query-generator.js:2440:25)
waiwai-backend    |     at Array.forEach (<anonymous>)
```

2024-12-01 16:14 UTC, mamepon2580 commented on src/repositories/sequelize-mysql/ReminderRepositoryImpl.ts
> +			deletedAt: null,
逆に以下のSQLはparameter指定されているのにundefinedで大丈夫そうですね！
```
waiwai-backend    | Executing (d76b8c91-63b0-42f1-9138-6b78ad2087ce): START TRANSACTION;
waiwai-backend    | Executing (d76b8c91-63b0-42f1-9138-6b78ad2087ce): INSERT INTO `Reminders` (`id`,`channelId`,`userId`,`receiveUserName`,`message`,`remindAt`,`createdAt`,`updatedAt`) VALUES (DEFAULT,?,?,?,?,?,?,?); params:{1141815610087583794,611950584085610504,<@1300829972965097472>,aaaaa,2024-12-01 16:30:00,2024-12-01 16:12:10,2024-12-01 16:12:10}
waiwai-backend    | Executing (d76b8c91-63b0-42f1-9138-6b78ad2087ce): COMMIT;
```

2024-12-01 16:14 UTC, y1wtt commented on src/repositories/sequelize-mysql/ReminderSchedulerRepositoryImpl.ts
> +				deletedAt: null,
https://sequelize.org/docs/v6/core-concepts/paranoid/#deleting
そもそもdeletedAt指定する必要ないですね

2024-12-01 16:33 UTC, mamepon2580 commented on src/repositories/sequelize-mysql/ReminderSchedulerRepositoryImpl.ts
> +				deletedAt: null,
そもそもparanoid: trueで自動的にWHERE `deletedAt` IS NULLがついていたので削除しました！

commit log: https://github.com/waiwai-developers/waiwaichan/pull/318/commits/308e4cc10f2343a097970d9f776a0160c894a1c9

2024-12-01 16:33 UTC, mamepon2580 commented on src/repositories/sequelize-mysql/ReminderRepositoryImpl.ts
> +				deletedAt: null,
そもそもparanoid: trueで自動的にWHERE `deletedAt` IS NULLがついていたので削除しました！

commit log: https://github.com/waiwai-developers/waiwaichan/pull/318/commits/308e4cc10f2343a097970d9f776a0160c894a1c9

2024-12-01 16:33 UTC, mamepon2580 commented on src/repositories/sequelize-mysql/ReminderRepositoryImpl.ts
> +			deletedAt: null,
そもそもparanoid: trueで自動的にWHERE `deletedAt` IS NULLがついていたので削除しました！

commit log: https://github.com/waiwai-developers/waiwaichan/pull/318/commits/308e4cc10f2343a097970d9f776a0160c894a1c9

2024-12-01 16:33 UTC, mamepon2580 commented on src/routes/discordjs/events/SlashCommandRouter.ts
> +									null,
こちら修正しました！

commit log: https://github.com/waiwai-developers/waiwaichan/pull/318/commits/308e4cc10f2343a097970d9f776a0160c894a1c9

2024-12-01 16:33 UTC, mamepon2580 commented on src/entities/dto/ReminderDto.ts
> +		public id: ReminderId | null,
こちら修正しました！

commit log: https://github.com/waiwai-developers/waiwaichan/pull/318/commits/308e4cc10f2343a097970d9f776a0160c894a1c9

2024-12-01 16:35 UTC, y1wtt approved these changes
LGTM

2024-12-01 16:35 UTC, merged